language: node_js
node_js:
#  - "4"
#  - "6"
  - "8"
script: npm run $COMMAND
env:
  - COMMAND=lint
  - COMMAND=test
  - COMMAND=build
  - COMMAND=build:integration
  #- COMMAND=test:karma-travis
before_install:
  - "npm set legacy-bundling=true"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
services:
  - xvfb
